# Generated by Django 5.2.4 on 2025-07-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_goal_due_date_goal_target_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="investment_horizon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="major_life_events",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="primary_goal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="primary_goal_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="risk_comfort",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="secondary_goal_timeline",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="secondary_goals",
            field=models.TextField(blank=True, null=True),
        ),
    ]
